import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from "react";
import { useAppState } from "../state/AppContext";
const prettyDateTime = (value) => new Date(value).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
});
export function AssetBookingPanel({ assetId }) {
    const { availability, bookingForm, createBooking, loadAvailability, selectedDate, selectDate, setBookingForm, } = useAppState();
    useEffect(() => {
        void loadAvailability(assetId, selectedDate);
    }, [assetId, selectedDate]);
    return (_jsxs("div", { className: "booking-layout", children: [_jsxs("section", { className: "panel stack", children: [_jsx("div", { className: "section-header", children: _jsxs("div", { children: [_jsx("p", { className: "eyebrow", children: "Availability" }), _jsx("h2", { children: "Plan your booking window" })] }) }), _jsxs("label", { className: "stack", children: [_jsx("span", { children: "Check date" }), _jsx("input", { type: "date", value: selectedDate, onChange: (event) => selectDate(event.target.value) })] }), availability ? (_jsxs("div", { className: "stack", children: [_jsxs("div", { children: [_jsx("p", { className: "label", children: "Available windows" }), availability.windows.length ? (availability.windows.map((window) => (_jsxs("div", { className: "time-row", children: [_jsx("strong", { children: prettyDateTime(window.startAt) }), _jsx("span", { children: prettyDateTime(window.endAt) })] }, window.startAt)))) : (_jsx("p", { children: "No configured availability on this date." }))] }), _jsxs("div", { children: [_jsx("p", { className: "label", children: "Active requests" }), availability.bookings.length ? (availability.bookings.map((booking) => (_jsxs("div", { className: "time-row", children: [_jsx("strong", { children: prettyDateTime(booking.startAt) }), _jsx("span", { children: booking.status })] }, booking.id)))) : (_jsx("p", { children: "No active bookings on this date." }))] })] })) : (_jsx("p", { children: "Availability loads when the asset page opens." }))] }), _jsxs("form", { className: "panel booking-panel stack", onSubmit: (event) => void createBooking(event, assetId), children: [_jsx("div", { className: "section-header", children: _jsxs("div", { children: [_jsx("p", { className: "eyebrow", children: "Booking request" }), _jsx("h2", { children: "Request this asset" })] }) }), _jsx("input", { value: bookingForm.contactName, onChange: (event) => setBookingForm({ ...bookingForm, contactName: event.target.value }), placeholder: "Contact name" }), _jsx("input", { value: bookingForm.contactEmail, onChange: (event) => setBookingForm({ ...bookingForm, contactEmail: event.target.value }), placeholder: "Contact email" }), _jsx("input", { type: "datetime-local", value: bookingForm.startAt.slice(0, 16), onChange: (event) => setBookingForm({ ...bookingForm, startAt: new Date(event.target.value).toISOString() }) }), _jsx("input", { type: "datetime-local", value: bookingForm.endAt.slice(0, 16), onChange: (event) => setBookingForm({ ...bookingForm, endAt: new Date(event.target.value).toISOString() }) }), _jsx("textarea", { value: bookingForm.notes, onChange: (event) => setBookingForm({ ...bookingForm, notes: event.target.value }), placeholder: "Event notes, delivery instructions, or setup details" }), _jsx("button", { type: "submit", children: "Submit booking request" })] })] }));
}
