import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink, Navigate, Outlet } from "react-router-dom";
import { useAppState } from "../state/AppContext";
export function WorkspaceLayout() {
    const { session, signOut, ownerBookings } = useAppState();
    if (!session) {
        return _jsx(Navigate, { to: "/app/login", replace: true });
    }
    const pendingCount = ownerBookings.filter((b) => b.status === "pending").length;
    return (_jsxs("div", { className: "workspace-layout", children: [_jsxs("aside", { className: "workspace-sidebar", children: [_jsxs("div", { className: "sidebar-logo", children: ["scan", _jsx("span", { children: "Ya" })] }), _jsxs("nav", { className: "sidebar-nav", children: [_jsx(NavLink, { to: "/app", end: true, className: ({ isActive }) => `sidebar-link ${isActive ? "sidebar-link--active" : ""}`, children: "Dashboard" }), _jsx(NavLink, { to: "/app/assets", className: ({ isActive }) => `sidebar-link ${isActive ? "sidebar-link--active" : ""}`, children: "My Assets" }), _jsxs(NavLink, { to: "/app/bookings", className: ({ isActive }) => `sidebar-link ${isActive ? "sidebar-link--active" : ""}`, children: ["Bookings", pendingCount > 0 && _jsx("span", { className: "sidebar-badge", children: pendingCount })] }), _jsx(NavLink, { to: "/app/qr", className: ({ isActive }) => `sidebar-link ${isActive ? "sidebar-link--active" : ""}`, children: "QR Codes" })] }), _jsxs("div", { className: "sidebar-user", children: [_jsx("div", { className: "sidebar-user-name", children: session.user.name }), _jsx("div", { className: "sidebar-user-role", children: "Asset Owner" }), _jsx("button", { className: "sidebar-signout", onClick: signOut, children: "Sign out" })] })] }), _jsx("div", { className: "workspace-main", children: _jsx(Outlet, {}) }), _jsxs("nav", { className: "workspace-bottom-tabs", children: [_jsxs(NavLink, { to: "/app", end: true, className: ({ isActive }) => `tab-link ${isActive ? "tab-link--active" : ""}`, children: [_jsx("span", { className: "tab-icon", children: "\u2302" }), "Home"] }), _jsxs(NavLink, { to: "/app/assets", className: ({ isActive }) => `tab-link ${isActive ? "tab-link--active" : ""}`, children: [_jsx("span", { className: "tab-icon", children: "\u25A2" }), "Assets"] }), _jsxs(NavLink, { to: "/app/bookings", className: ({ isActive }) => `tab-link ${isActive ? "tab-link--active" : ""}`, children: [_jsx("span", { className: "tab-icon", children: "\uD83D\uDCC5" }), "Bookings", pendingCount > 0 && _jsx("span", { className: "tab-badge", children: pendingCount })] }), _jsxs(NavLink, { to: "/app/qr", className: ({ isActive }) => `tab-link ${isActive ? "tab-link--active" : ""}`, children: [_jsx("span", { className: "tab-icon", children: "\u25A9" }), "QR"] }), _jsxs(NavLink, { to: "/app/profile", className: ({ isActive }) => `tab-link ${isActive ? "tab-link--active" : ""}`, children: [_jsx("span", { className: "tab-icon", children: "\u263B" }), "Profile"] })] })] }));
}
